Rename to span to loc

diff --git a/myter/scripts/run b/myter/scripts/run
--- a/myter/scripts/run
+++ b/myter/scripts/run
@@ -1,3 +1,8 @@
 #!/bin/bash
 
-$MYTEPATH/myter/target/debug/myter $@
+if [[ "$(basename $(pwd))" != "myter" ]]; then
+  echo "Error: Must run from myter directory"
+  exit 1
+fi
+
+./target/debug/myter $@
